// Mock content used by every page. No backend, no copyrighted text.
// Each item carries `tags` and `intents` so the personalization engine
// can score and explain matches.

import type { Article, CreditCard, Deal, Destination } from "./types";

export const ARTICLES: Article[] = [
  {
    slug: "points-miles-101",
    category: "Guide",
    title: "Points and Miles 101: Your first 90 days",
    excerpt:
      "A no-jargon roadmap for turning everyday spending into your first free flight — without overspending.",
    readTime: "6 min read",
    hero: "from-tpg-blue to-tpg-teal",
    tags: ["beginner", "card-strategy"],
    intents: ["learning"],
    body: [
      "If you're new to points and miles, the first 90 days are about building good habits — not chasing every bonus.",
      "Start with one no-annual-fee card, focus on a single transferable currency, and earn your first 30,000 points before you even think about a premium product.",
      "By the time you've finished this guide, you'll know how to evaluate a welcome bonus, what 'transferable points' actually means, and how to redeem your first award flight with confidence.",
    ],
  },
  {
    slug: "japan-on-points",
    category: "Guide",
    title: "How to fly to Japan in business class on points",
    excerpt:
      "Three sweet-spot routings, the best transfer partners for each, and exactly how many points you need.",
    readTime: "9 min read",
    hero: "from-rose-500 to-amber-400",
    tags: ["japan", "premium-cabin", "award-bookings", "transfer-partners", "intermediate"],
    intents: ["trip-planning", "maximizing"],
    body: [
      "Japan is one of the most rewarding redemptions in the points world — and one of the easiest to book if you know which programs to use.",
      "The sweet spot starts at 60,000 miles one-way in business class through a major alliance partner. Add a stopover in a hub city to stretch your award further.",
      "Below is a worked example: how a beginner traveler turns a single welcome bonus into two business-class tickets to Tokyo with cherry-blossom timing.",
    ],
  },
  {
    slug: "beginner-card-pairings",
    category: "Strategy",
    title: "The simplest two-card combo for beginners",
    excerpt:
      "Pair the right entry-level card with one workhorse for everyday spend and earn 2-3x almost everywhere.",
    readTime: "5 min read",
    hero: "from-tpg-navy to-tpg-blue",
    tags: ["beginner", "card-strategy", "dining", "groceries"],
    intents: ["learning", "card-shopping"],
    body: [
      "You don't need a wallet full of premium cards to earn meaningful rewards.",
      "This combo gives you 3x on dining, 2x on groceries, and a transferable currency you can move to over a dozen airline and hotel partners.",
      "We'll walk through the spend pattern of a typical household and show what you'd earn in a year.",
    ],
  },
  {
    slug: "all-inclusive-resorts",
    category: "Guide",
    title: "Best all-inclusive resorts you can book with points",
    excerpt:
      "Eight properties from Mexico to the Maldives where your points stretch the furthest in 2026.",
    readTime: "7 min read",
    hero: "from-tpg-teal to-emerald-400",
    tags: ["luxury-hotels", "caribbean", "hyatt", "marriott", "intermediate"],
    intents: ["trip-planning", "deal-hunting"],
    body: [
      "All-inclusive doesn't have to mean all-cash. A handful of point properties deliver a sky-high cents-per-point value if you book the right week.",
      "Below: eight resorts ranked by points-per-night and value, with the best months to lock in availability.",
    ],
  },
  {
    slug: "dining-multipliers",
    category: "Strategy",
    title: "Cards that earn the most on dining (and how to stack them)",
    excerpt:
      "If dining is a top three category for you, these multipliers compound fast — here's the smartest stack.",
    readTime: "4 min read",
    hero: "from-amber-500 to-rose-500",
    tags: ["dining", "card-strategy", "card-comparison", "intermediate"],
    intents: ["card-shopping", "maximizing", "card-comparison"],
    body: [
      "Dining is the single biggest accelerator in most rewards portfolios.",
      "Three cards stand out, each with a different angle: a transferable workhorse, a category-bonus play, and a premium card with credits that effectively rebate the annual fee.",
    ],
  },
  {
    slug: "europe-summer-sweet-spots",
    category: "Guide",
    title: "Europe this summer: 5 award sweet spots before they're gone",
    excerpt:
      "Award space to Lisbon, Athens, and Rome is opening up — here's how to grab it.",
    readTime: "6 min read",
    hero: "from-sky-500 to-tpg-blue",
    tags: ["europe", "italy", "award-bookings", "premium-cabin"],
    intents: ["trip-planning", "deal-hunting"],
    body: [
      "European summer award space is famously tight — but a handful of programs are quietly releasing dates for June and July.",
      "We track the patterns daily and break down five sweet spots you can still book today.",
    ],
  },
  {
    slug: "lounge-access-guide",
    category: "Guide",
    title: "The 2026 airport lounge access guide",
    excerpt:
      "Which premium cards still get you into which networks — and which are worth the annual fee.",
    readTime: "8 min read",
    hero: "from-tpg-navy to-tpg-teal",
    tags: ["lounges", "premium-cabin", "card-comparison", "advanced"],
    intents: ["card-comparison", "card-shopping"],
    body: [
      "Lounge access has gotten more complicated — and more valuable.",
      "We rank the major networks, then map each premium card to the lounges it actually opens, with caveats on guest policies and capacity controls.",
    ],
  },
  {
    slug: "transfer-bonus-watch",
    category: "Deal",
    title: "This week's transfer bonus alerts (up to 40% off)",
    excerpt:
      "Three transfer promotions worth acting on — and one to skip even though it looks tempting.",
    readTime: "3 min read",
    hero: "from-tpg-teal-deep to-tpg-blue",
    tags: ["deals", "transfer-partners", "advanced"],
    intents: ["deal-hunting", "maximizing"],
    body: [
      "Transfer bonuses are the single fastest way to stretch your points — but only when paired with confirmed award space.",
      "Three deals are worth your attention this week. One is a trap.",
    ],
  },
  {
    slug: "family-travel-points",
    category: "Guide",
    title: "How to fly a family of four on points without going broke",
    excerpt:
      "Award bookings get harder with kids — these five strategies still work in 2026.",
    readTime: "7 min read",
    hero: "from-pink-500 to-tpg-blue",
    tags: ["family-travel", "beginner", "award-bookings"],
    intents: ["trip-planning", "learning"],
    body: [
      "Two adults plus two kids is the hardest party size to book on points — but not impossible.",
      "Here are five tested strategies, in order of how realistic they are if you're starting from zero.",
    ],
  },
  {
    slug: "iceland-northern-lights",
    category: "Guide",
    title: "Chasing the Northern Lights in Iceland on points",
    excerpt:
      "Award sweet spots to Reykjavík, plus the hotel chains with the best aurora-zone properties.",
    readTime: "6 min read",
    hero: "from-indigo-500 to-tpg-teal",
    tags: ["iceland", "trip-planning", "award-bookings"],
    intents: ["trip-planning"],
    body: [
      "Iceland is a year-round redemption favorite, but late winter is peak aurora season.",
      "Here's the playbook: where to fly into, which chain has the best northern-lights properties, and when to book.",
    ],
  },
  {
    slug: "hawaii-on-miles",
    category: "Guide",
    title: "Hawaii on miles: still possible in 2026",
    excerpt:
      "Award space tightened — but these programs still get you to the islands for under 25k miles one-way.",
    readTime: "5 min read",
    hero: "from-emerald-500 to-tpg-teal",
    tags: ["hawaii", "award-bookings", "beginner"],
    intents: ["trip-planning", "learning"],
    body: [
      "Hawaii used to be a beginner-friendly redemption. It still is — if you know which programs to look at first.",
      "We rank the four best programs for Hawaii award flights and explain the trade-offs of each.",
    ],
  },
  {
    slug: "premium-card-showdown",
    category: "Review",
    title: "Premium card showdown: which $695 card actually earns its fee?",
    excerpt:
      "Three premium cards, one annual fee benchmark, and a brutally honest scorecard.",
    readTime: "10 min read",
    hero: "from-tpg-navy-deep to-tpg-blue",
    tags: ["card-comparison", "lounges", "premium-cabin", "advanced"],
    intents: ["card-comparison", "card-shopping"],
    body: [
      "Three premium cards. One head-to-head. We score each on lounge access, statement credits, transfer partners, and real-world earning rates.",
      "By the end you'll know which one — if any — earns its keep in your wallet.",
    ],
  },
  {
    slug: "five-rookie-mistakes",
    category: "Strategy",
    title: "Five rookie mistakes that cost beginners points",
    excerpt:
      "We've audited hundreds of new-user wallets. The same five mistakes show up in almost every one.",
    readTime: "4 min read",
    hero: "from-rose-500 to-tpg-blue",
    tags: ["beginner", "card-strategy"],
    intents: ["learning"],
    body: [
      "Most beginners lose 30–40% of their first-year earning potential to a handful of avoidable mistakes.",
      "We rank them by impact, then show the simplest fix for each.",
    ],
  },
  {
    slug: "welcome-bonuses-demystified",
    category: "Guide",
    title: "Welcome bonuses, demystified in 4 minutes",
    excerpt:
      "What 'spend $4,000 in 3 months' actually means, how to plan your spend, and the trap most new applicants fall into.",
    readTime: "4 min read",
    hero: "from-sky-500 to-tpg-blue",
    tags: ["beginner", "card-strategy"],
    intents: ["learning", "card-shopping"],
    body: [
      "Welcome bonuses are how almost every points strategy gets seeded. But the headline number isn't the whole story.",
      "Below: what to look for, what to ignore, and the timing mistake that costs people their bonus entirely.",
    ],
  },
  {
    slug: "annual-fee-math",
    category: "Strategy",
    title: "Annual fees: when to swallow them, when to dodge",
    excerpt:
      "A clean framework for deciding whether a card's annual fee earns its keep in your wallet.",
    readTime: "5 min read",
    hero: "from-tpg-navy to-tpg-blue",
    tags: ["card-comparison", "card-strategy", "intermediate"],
    intents: ["card-comparison", "card-shopping"],
    body: [
      "We break down four ways to value an annual fee — and which one actually predicts whether you'll keep the card past year one.",
      "Includes a quick scorecard you can apply to any card in 90 seconds.",
    ],
  },
  {
    slug: "first-transfer-partner",
    category: "Guide",
    title: "Your first transfer partner: a beginner's playbook",
    excerpt:
      "Don't transfer points blindly. Here's how to pick your first partner — and the four questions to ask before you hit the button.",
    readTime: "6 min read",
    hero: "from-tpg-teal to-emerald-400",
    tags: ["beginner", "transfer-partners"],
    intents: ["learning", "trip-planning"],
    body: [
      "Transferring points is a one-way trip — you can't undo it once it lands at an airline or hotel.",
      "We walk through four questions every transfer should answer before you confirm.",
    ],
  },
  {
    slug: "avios-short-haul",
    category: "Strategy",
    title: "British Airways Avios: the short-haul hack still works",
    excerpt:
      "Avios remain the best currency for sub-2,000-mile flights — here's the routing playbook nobody else writes about.",
    readTime: "6 min read",
    hero: "from-indigo-500 to-tpg-blue",
    tags: ["transfer-partners", "award-bookings", "advanced", "europe"],
    intents: ["maximizing", "trip-planning"],
    body: [
      "BA Avios pricing on short-haul partner segments hasn't moved in three years — making it the most consistent sweet spot in the entire program.",
      "We map the routes that still deliver under 9,000 miles one-way in economy.",
    ],
  },
  {
    slug: "lufthansa-first-class",
    category: "Strategy",
    title: "Lufthansa first class for 87k miles: still real?",
    excerpt:
      "The most coveted award in the points game — but only if you can find the seat. Here's the 2026 booking pattern.",
    readTime: "8 min read",
    hero: "from-amber-500 to-rose-500",
    tags: ["premium-cabin", "award-bookings", "advanced", "europe"],
    intents: ["maximizing", "trip-planning"],
    body: [
      "Lufthansa releases first-class partner award space within 14 days of departure — a maddening rule that nonetheless creates predictable windows.",
      "We tracked space for six months. Here's exactly when seats appear, which programs see them first, and how to be ready.",
    ],
  },
  {
    slug: "aeroplan-underrated",
    category: "Guide",
    title: "Air Canada Aeroplan: the program everyone underestimates",
    excerpt:
      "More partners than Amex MR, dynamic pricing that's actually fair, and stopover rules that save 20k miles.",
    readTime: "7 min read",
    hero: "from-tpg-blue to-tpg-teal-deep",
    tags: ["transfer-partners", "award-bookings", "intermediate"],
    intents: ["maximizing", "trip-planning"],
    body: [
      "Most US-based points enthusiasts skip Aeroplan because the dashboard looks dated. That's a mistake.",
      "We rank Aeroplan's strongest sweet spots in 2026, and show why their stopover rule alone is worth the transfer.",
    ],
  },
  {
    slug: "finding-award-space",
    category: "Strategy",
    title: "How to find award space when search engines lie",
    excerpt:
      "Three free tools, two paid ones, and the workflow we use to surface seats other shoppers can't see.",
    readTime: "9 min read",
    hero: "from-tpg-navy-deep to-tpg-blue",
    tags: ["award-bookings", "advanced", "premium-cabin"],
    intents: ["maximizing", "trip-planning"],
    body: [
      "Award search engines miss a surprising amount of inventory — especially partner space that doesn't show up unless you query the right program.",
      "Our workflow combines three free aggregators with two phone-only tricks. We walk through a real Tokyo booking start to finish.",
    ],
  },
  {
    slug: "stopovers-open-jaws",
    category: "Guide",
    title: "Stopovers & open jaws: the routings no one talks about",
    excerpt:
      "Why a Tokyo trip can include 4 days in Vancouver for the same number of miles. Eight programs ranked.",
    readTime: "7 min read",
    hero: "from-tpg-teal to-tpg-blue",
    tags: ["award-bookings", "intermediate", "trip-planning"],
    intents: ["trip-planning", "maximizing"],
    body: [
      "Stopovers turn a one-way award into a two-city trip at no extra cost. Open jaws let you fly into one city and out of another.",
      "Eight programs still allow these. We rank them by flexibility — and call out the three that quietly removed the perk.",
    ],
  },
  {
    slug: "sapphire-vs-gold-real-test",
    category: "Review",
    title: "Chase Sapphire vs Amex Gold: a real-world test",
    excerpt:
      "We tracked one year of identical spending on both cards. The winner surprised us — and probably will surprise you.",
    readTime: "10 min read",
    hero: "from-tpg-navy to-tpg-teal",
    tags: ["card-comparison", "dining", "chase", "amex", "intermediate"],
    intents: ["card-comparison", "card-shopping"],
    body: [
      "Twelve months. $48,000 in spend on each card. Identical purchases.",
      "We measured raw points earned, transfer redemption value, and credit-recouped value. The gap was bigger than expected.",
    ],
  },
  {
    slug: "two-card-combos-2026",
    category: "Strategy",
    title: "Two-card combos that beat the premium card crowd",
    excerpt:
      "$295 in annual fees, an effective 4x on every category that matters, and access to two transferable currencies.",
    readTime: "8 min read",
    hero: "from-emerald-500 to-tpg-blue",
    tags: ["card-comparison", "card-strategy", "intermediate"],
    intents: ["card-shopping", "maximizing", "card-comparison"],
    body: [
      "You don't need a $695 card to play at the top table. Two well-paired cards can match or beat a premium loadout for half the annual fee.",
      "We rank the eight best two-card combos in 2026, by household spend pattern.",
    ],
  },
  {
    slug: "5-24-explained",
    category: "Guide",
    title: "5/24, explained without the jargon",
    excerpt:
      "Chase's unwritten rule that quietly governs almost every premium card approval — and how to work with it.",
    readTime: "5 min read",
    hero: "from-sky-500 to-tpg-navy",
    tags: ["card-strategy", "chase", "intermediate"],
    intents: ["card-shopping", "learning"],
    body: [
      "Chase doesn't publish the 5/24 rule. They don't even confirm it exists. But every approval modeled in our database respects it.",
      "We explain how to count, how to plan around it, and the three card types it doesn't apply to.",
    ],
  },
  {
    slug: "retention-offers-script",
    category: "Strategy",
    title: "How to negotiate retention offers — script included",
    excerpt:
      "The 90-second phone call that's saved our readers an average of $180 per annual-fee card.",
    readTime: "4 min read",
    hero: "from-amber-500 to-tpg-teal-deep",
    tags: ["card-strategy", "advanced"],
    intents: ["maximizing"],
    body: [
      "Annual fees aren't fixed. Most issuers have a retention budget — they just don't volunteer it.",
      "We share the exact opening line our readers use, plus the three follow-up beats that actually unlock an offer.",
    ],
  },
  {
    slug: "tokyo-7-days-on-points",
    category: "Guide",
    title: "Tokyo in 7 days, all on points",
    excerpt:
      "Flights, hotels, JR Pass — yes, even the train. Here's the exact wallet that made this 7-day trip free.",
    readTime: "9 min read",
    hero: "from-rose-500 to-amber-400",
    tags: ["japan", "trip-planning", "award-bookings", "premium-cabin", "intermediate"],
    intents: ["trip-planning"],
    body: [
      "We built a complete 7-day Tokyo trip — flights, hotels, and ground transit — entirely on points.",
      "Below: the cards we used, the order we redeemed in, and the one expense we couldn't get free.",
    ],
  },
  {
    slug: "thailand-hyatt-playbook",
    category: "Guide",
    title: "Thailand on Hyatt points: the under-25k playbook",
    excerpt:
      "Four properties in Thailand still book for 20k Hyatt points a night. Here's how to chain them into one trip.",
    readTime: "6 min read",
    hero: "from-emerald-500 to-tpg-teal",
    tags: ["thailand", "hyatt", "luxury-hotels", "trip-planning"],
    intents: ["trip-planning", "deal-hunting"],
    body: [
      "Hyatt's award chart still has gems in Southeast Asia — including four Thailand properties that punch well above their points cost.",
      "We map a 10-night itinerary that uses all four, ending in Phuket.",
    ],
  },
  {
    slug: "tuscany-on-miles",
    category: "Guide",
    title: "Tuscany on miles: best routings for the long way around",
    excerpt:
      "Direct flights to Florence are scarce on awards. These three routings get you there for the same miles and a better experience.",
    readTime: "7 min read",
    hero: "from-amber-500 to-rose-500",
    tags: ["italy", "europe", "award-bookings", "trip-planning"],
    intents: ["trip-planning"],
    body: [
      "Florence (FLR) is awarded sparingly across alliance programs. But three indirect routings consistently open seats — and let you build in a free European stopover.",
      "We map each, with the program best suited to each city pair.",
    ],
  },
  {
    slug: "lisbon-cheap-bookings",
    category: "Guide",
    title: "Lisbon is the new Barcelona — and cheaper to book",
    excerpt:
      "Award space to Lisbon has loosened in 2026 while every other European hub tightened. Here's why, and how to take advantage.",
    readTime: "5 min read",
    hero: "from-sky-500 to-tpg-blue",
    tags: ["europe", "award-bookings", "trip-planning", "premium-cabin"],
    intents: ["trip-planning", "deal-hunting"],
    body: [
      "TAP Portugal expanded its long-haul network this year and opened more partner award space than any other European carrier.",
      "Below: the four programs with the best Lisbon access, plus our top three Lisbon points hotels.",
    ],
  },
  {
    slug: "maui-inter-island-miles",
    category: "Guide",
    title: "Maui inter-island: cheapest miles redemptions in the US",
    excerpt:
      "Why a 30-minute hop between Hawaiian islands is one of the highest cents-per-point redemptions you can book in the country.",
    readTime: "4 min read",
    hero: "from-emerald-500 to-tpg-teal",
    tags: ["hawaii", "award-bookings", "beginner", "family-travel"],
    intents: ["trip-planning", "learning"],
    body: [
      "Inter-island flights in Hawaii price absurdly high in cash and absurdly low in miles — making them one of the best high-value, low-effort redemptions.",
      "We rank the three programs to use, with current cash vs miles pricing.",
    ],
  },
  {
    slug: "st-lucia-all-inclusive",
    category: "Guide",
    title: "St. Lucia all-inclusives: when points beat cash",
    excerpt:
      "Three resorts in St. Lucia book for under 40k points a night — including one that retails over $1,200.",
    readTime: "5 min read",
    hero: "from-tpg-teal to-emerald-400",
    tags: ["caribbean", "luxury-hotels", "marriott", "trip-planning"],
    intents: ["trip-planning", "deal-hunting"],
    body: [
      "Marriott's award chart for the Caribbean has been quietly forgiving — even after the program's 2023 dynamic-pricing pivot.",
      "Three St. Lucia properties remain genuine sweet spots. We cover dates, point sources, and one cautionary tale.",
    ],
  },
  {
    slug: "business-class-under-80k",
    category: "Guide",
    title: "Best business class seats under 80k miles",
    excerpt:
      "We ranked every business-class product available for under 80k miles one-way. Two surprised us; three were exactly as good as advertised.",
    readTime: "8 min read",
    hero: "from-tpg-navy-deep to-tpg-teal-deep",
    tags: ["premium-cabin", "award-bookings", "intermediate", "advanced"],
    intents: ["maximizing", "trip-planning"],
    body: [
      "Under-80k business class isn't dead — but it's less common, and the products vary more than ever.",
      "We flew (or re-flew) eleven of them this year. Here's the ranking, with notes on which programs book each.",
    ],
  },
  {
    slug: "priority-pass-2026",
    category: "Review",
    title: "Priority Pass in 2026: which cards still get you in",
    excerpt:
      "Priority Pass kept changing — and so did the cards that include it. Here's the updated card-by-card breakdown.",
    readTime: "6 min read",
    hero: "from-tpg-blue to-tpg-navy",
    tags: ["lounges", "card-comparison", "premium-cabin", "intermediate"],
    intents: ["card-comparison", "card-shopping"],
    body: [
      "Priority Pass coverage is no longer a flat 'in or out' question — guest rules, restaurant access, and lounge bans now differ card to card.",
      "We map the current rules across the eight major Priority Pass-bundling cards.",
    ],
  },
  {
    slug: "capital-one-lounge-review",
    category: "Review",
    title: "Capital One Lounge Network: a year-one review",
    excerpt:
      "Four locations, one of the strongest food menus in any US airport lounge, and a guest policy that puts other premium cards on notice.",
    readTime: "7 min read",
    hero: "from-tpg-teal-deep to-tpg-blue",
    tags: ["lounges", "capital-one", "premium-cabin", "advanced"],
    intents: ["card-comparison", "card-shopping"],
    body: [
      "We visited every Capital One Lounge in its first year of operation. The food alone is reason to keep the Venture X in your wallet.",
      "Below: the unfiltered notes from each location, plus how the network compares to Amex Centurion and Chase Sapphire Lounges.",
    ],
  },
  {
    slug: "hyatt-globalist-fast-paths",
    category: "Strategy",
    title: "Hyatt Globalist: the fastest paths in 2026",
    excerpt:
      "60 nights is the published threshold. Here are the four shortcuts that get most readers there in fewer than 40 paid nights.",
    readTime: "6 min read",
    hero: "from-emerald-500 to-tpg-teal-deep",
    tags: ["hyatt", "luxury-hotels", "advanced"],
    intents: ["maximizing"],
    body: [
      "Globalist is the most rewarding hotel status in the points game — and the most under-the-radar to earn quickly.",
      "We rank the four legitimate shortcuts, including one that almost nobody talks about.",
    ],
  },
  {
    slug: "united-excursionist-perk",
    category: "Guide",
    title: "United Excursionist: still the best perk nobody uses",
    excerpt:
      "An entire free award segment hiding inside any round-trip United booking. We walk through three real bookings.",
    readTime: "6 min read",
    hero: "from-tpg-blue to-tpg-navy-deep",
    tags: ["united", "award-bookings", "intermediate", "trip-planning"],
    intents: ["maximizing", "trip-planning"],
    body: [
      "United's Excursionist Perk effectively gives you a free third segment on most multi-destination award bookings. The rules are dense — but the value is real.",
      "Three worked examples follow, including the small modification that maximizes value.",
    ],
  },
  {
    slug: "marriott-2026-worth-it",
    category: "Strategy",
    title: "Marriott Bonvoy in 2026: still worth optimizing?",
    excerpt:
      "After three years of dynamic-pricing pivots, we put Bonvoy's actual award value to the test.",
    readTime: "8 min read",
    hero: "from-amber-500 to-tpg-blue",
    tags: ["marriott", "luxury-hotels", "card-comparison"],
    intents: ["card-comparison", "maximizing"],
    body: [
      "Bonvoy's earning rate is still strong. Its redemption rate is more questionable than ever.",
      "We computed effective points-per-dollar across the program's top 40 properties this year. The math is sobering — but actionable.",
    ],
  },
  {
    slug: "family-of-four-real-spend",
    category: "Guide",
    title: "Family of four on points: real spend, real itineraries",
    excerpt:
      "Three years of one family's points strategy, the cards they kept, and the trips they actually took.",
    readTime: "10 min read",
    hero: "from-pink-500 to-tpg-blue",
    tags: ["family-travel", "beginner", "trip-planning", "card-strategy"],
    intents: ["trip-planning", "learning"],
    body: [
      "We embedded with one family for three years. They earned 1.2M points across two adults and never paid for an annual fee twice in a row.",
      "Below: the exact card lineup, the trips they redeemed for, and the two mistakes they wish they hadn't made.",
    ],
  },
  {
    slug: "solo-travel-cards",
    category: "Strategy",
    title: "Solo travel rewards: cards & programs that don't penalize you",
    excerpt:
      "Most rewards programs quietly favor couples and families. Six that work just as well — or better — for solo travelers.",
    readTime: "5 min read",
    hero: "from-fuchsia-500 to-tpg-blue",
    tags: ["solo-travel", "card-strategy", "intermediate"],
    intents: ["card-shopping"],
    body: [
      "If you travel solo, you may have noticed certain redemptions are quietly more expensive — companion fares, double-occupancy hotel awards, household point pooling.",
      "We rank six cards and three programs that don't punish solo travelers.",
    ],
  },
  {
    slug: "devaluation-watch-2026",
    category: "News",
    title: "Devaluation watch: programs we expect to change in 2026",
    excerpt:
      "Three programs are due for a hike based on the past five years of data. Here's how to act before they do.",
    readTime: "5 min read",
    hero: "from-tpg-navy-deep to-rose-500",
    tags: ["advanced", "deals", "transfer-partners"],
    intents: ["maximizing", "deal-hunting"],
    body: [
      "We tracked the timing of every major devaluation across the top 12 programs. Three follow a strikingly predictable cadence.",
      "Below: which three to watch, and the specific awards to book before they shift.",
    ],
  },
];

export const CARDS: CreditCard[] = [
  {
    id: "tpg-sapphire-preferred",
    name: "Skyline Sapphire Preferred",
    issuer: "Chase",
    network: "Visa",
    annualFee: 95,
    bonusPoints: 60000,
    bonusRequirement: "Spend $4,000 in 3 months",
    highlights: ["3x dining", "2x travel", "Transfers to 14+ partners"],
    tags: ["beginner", "card-strategy", "dining", "travel-spend", "chase"],
    audience: "beginner",
    color: "from-tpg-blue to-tpg-navy",
  },
  {
    id: "tpg-gold",
    name: "Northstar Gold Rewards",
    issuer: "Amex",
    network: "Amex",
    annualFee: 250,
    bonusPoints: 75000,
    bonusRequirement: "Spend $6,000 in 6 months",
    highlights: ["4x dining", "4x groceries", "$120 dining credit"],
    tags: ["dining", "groceries", "amex", "card-strategy"],
    audience: "intermediate",
    color: "from-amber-500 to-tpg-teal-deep",
  },
  {
    id: "tpg-venture-x",
    name: "Compass Venture X",
    issuer: "Capital One",
    network: "Visa",
    annualFee: 395,
    bonusPoints: 75000,
    bonusRequirement: "Spend $4,000 in 3 months",
    highlights: ["2x everything", "Lounge access", "$300 travel credit"],
    tags: ["travel-spend", "lounges", "capital-one", "premium-cabin"],
    audience: "intermediate",
    color: "from-tpg-teal to-tpg-blue",
  },
  {
    id: "tpg-platinum",
    name: "Atlas Platinum Elite",
    issuer: "Amex",
    network: "Amex",
    annualFee: 695,
    bonusPoints: 80000,
    bonusRequirement: "Spend $8,000 in 6 months",
    highlights: ["5x flights", "1,400+ lounges", "Premium hotel status"],
    tags: ["lounges", "premium-cabin", "luxury-hotels", "amex", "advanced"],
    audience: "advanced",
    color: "from-tpg-navy-deep to-tpg-teal-deep",
  },
  {
    id: "tpg-united-club",
    name: "United Skylight Club Card",
    issuer: "Chase",
    network: "Visa",
    annualFee: 525,
    bonusPoints: 80000,
    bonusRequirement: "Spend $5,000 in 3 months",
    highlights: ["United Club access", "Free first bag", "Premier qualifying boost"],
    tags: ["united", "lounges", "premium-cabin", "advanced"],
    audience: "advanced",
    color: "from-tpg-blue to-tpg-navy-deep",
  },
  {
    id: "tpg-hyatt",
    name: "Hyatt Horizon Rewards",
    issuer: "Chase",
    network: "Visa",
    annualFee: 95,
    bonusPoints: 60000,
    bonusRequirement: "Spend $3,000 in 3 months",
    highlights: ["Free anniversary night", "4x at Hyatt", "Discoverist status"],
    tags: ["hyatt", "luxury-hotels", "chase"],
    audience: "intermediate",
    color: "from-emerald-500 to-tpg-blue",
  },
  {
    id: "tpg-freedom",
    name: "Skyline Freedom Starter",
    issuer: "Chase",
    network: "Visa",
    annualFee: 0,
    bonusPoints: 20000,
    bonusRequirement: "Spend $500 in 3 months",
    highlights: ["No annual fee", "5x rotating categories", "Pairs with Sapphire"],
    tags: ["beginner", "card-strategy", "chase", "budget"],
    audience: "beginner",
    color: "from-sky-500 to-tpg-blue",
  },
  {
    id: "tpg-sapphire-reserve",
    name: "Skyline Sapphire Reserve",
    issuer: "Chase",
    network: "Visa",
    annualFee: 550,
    bonusPoints: 75000,
    bonusRequirement: "Spend $4,000 in 3 months",
    highlights: ["3x dining & travel", "$300 travel credit", "Priority Pass + Sapphire Lounges"],
    tags: ["chase", "premium-cabin", "lounges", "dining", "travel-spend", "advanced"],
    audience: "advanced",
    color: "from-tpg-navy-deep to-tpg-blue",
  },
  {
    id: "tpg-delta-reserve",
    name: "Delta Sky Crown Reserve",
    issuer: "Amex",
    network: "Amex",
    annualFee: 650,
    bonusPoints: 80000,
    bonusRequirement: "Spend $5,000 in 3 months",
    highlights: ["Sky Club access", "Companion certificate", "Status boost"],
    tags: ["delta", "lounges", "premium-cabin", "amex", "advanced"],
    audience: "advanced",
    color: "from-rose-600 to-tpg-navy",
  },
  {
    id: "tpg-aa-exec",
    name: "American Apex Executive",
    issuer: "Citi",
    network: "Mastercard",
    annualFee: 595,
    bonusPoints: 70000,
    bonusRequirement: "Spend $6,000 in 4 months",
    highlights: ["Admirals Club access", "Loyalty Point boost", "$120 Global Entry credit"],
    tags: ["american", "lounges", "premium-cabin", "advanced"],
    audience: "advanced",
    color: "from-sky-700 to-tpg-navy",
  },
  {
    id: "tpg-bonvoy-bold",
    name: "Bonvoy Boundless Plus",
    issuer: "Chase",
    network: "Visa",
    annualFee: 95,
    bonusPoints: 60000,
    bonusRequirement: "Spend $3,000 in 3 months",
    highlights: ["Free anniversary night (35k)", "6x at Marriott", "Silver elite status"],
    tags: ["marriott", "luxury-hotels", "chase", "intermediate"],
    audience: "intermediate",
    color: "from-amber-500 to-rose-500",
  },
  {
    id: "tpg-aa-platinum",
    name: "American Apex Platinum",
    issuer: "Citi",
    network: "Mastercard",
    annualFee: 99,
    bonusPoints: 50000,
    bonusRequirement: "Spend $2,500 in 3 months",
    highlights: ["2x dining & gas", "Free first bag on American", "No foreign transaction fees"],
    tags: ["american", "dining", "gas", "travel-spend", "intermediate"],
    audience: "intermediate",
    color: "from-tpg-blue to-tpg-navy",
  },
  {
    id: "tpg-amex-green",
    name: "Northstar Green Rewards",
    issuer: "Amex",
    network: "Amex",
    annualFee: 150,
    bonusPoints: 40000,
    bonusRequirement: "Spend $3,000 in 6 months",
    highlights: ["3x travel & dining", "CLEAR credit", "Transfers to 19+ partners"],
    tags: ["amex", "dining", "travel-spend", "transfer-partners", "intermediate"],
    audience: "intermediate",
    color: "from-emerald-500 to-tpg-teal-deep",
  },
  {
    id: "tpg-quicksilver",
    name: "Compass Quicksilver",
    issuer: "Capital One",
    network: "Mastercard",
    annualFee: 0,
    bonusPoints: 25000,
    bonusRequirement: "Spend $500 in 3 months",
    highlights: ["1.5% on everything", "No annual fee", "No foreign transaction fees"],
    tags: ["capital-one", "beginner", "budget", "travel-spend"],
    audience: "beginner",
    color: "from-tpg-gold to-amber-500",
  },
  {
    id: "tpg-blue-cash",
    name: "Northstar Blue Cash Everyday",
    issuer: "Amex",
    network: "Amex",
    annualFee: 0,
    bonusPoints: 30000,
    bonusRequirement: "Spend $2,000 in 6 months",
    highlights: ["3% groceries", "3% gas", "3% online retail"],
    tags: ["amex", "groceries", "gas", "beginner", "budget"],
    audience: "beginner",
    color: "from-sky-500 to-tpg-blue-soft",
  },
  {
    id: "tpg-ink-business",
    name: "Skyline Ink Business Plus",
    issuer: "Chase",
    network: "Visa",
    annualFee: 95,
    bonusPoints: 90000,
    bonusRequirement: "Spend $6,000 in 3 months",
    highlights: ["5x on office supplies & internet", "2x at gas + dining", "Pairs with Sapphire"],
    tags: ["chase", "card-strategy", "transfer-partners", "intermediate"],
    audience: "intermediate",
    color: "from-tpg-navy to-tpg-teal-deep",
  },
  {
    id: "tpg-united-club-business",
    name: "United Skylight Business",
    issuer: "Chase",
    network: "Visa",
    annualFee: 99,
    bonusPoints: 75000,
    bonusRequirement: "Spend $5,000 in 3 months",
    highlights: ["2x United purchases", "Free checked bag", "United Club passes"],
    tags: ["united", "lounges", "travel-spend", "intermediate"],
    audience: "intermediate",
    color: "from-tpg-blue to-tpg-navy",
  },
];

export const DEALS: Deal[] = [
  {
    id: "deal-amex-virgin",
    title: "30% transfer bonus to Virgin partners",
    partner: "Amex → Virgin",
    endsOn: "Ends in 6 days",
    perk: "Move 50k → get 65k miles",
    tags: ["transfer-partners", "deals", "advanced"],
  },
  {
    id: "deal-hyatt-bonus",
    title: "Hyatt: double points on stays in Tokyo & Kyoto",
    partner: "World of Hyatt",
    endsOn: "Through Aug 31",
    perk: "2x base + bonus on eligible nights",
    tags: ["hyatt", "japan", "luxury-hotels", "deals"],
  },
  {
    id: "deal-summer-europe",
    title: "Summer Europe award space released",
    partner: "Multiple alliances",
    endsOn: "Limited release",
    perk: "Business class from 60k one-way",
    tags: ["europe", "italy", "award-bookings", "deals", "premium-cabin"],
  },
  {
    id: "deal-cap-one-bonus",
    title: "Capital One: 25% transfer bonus to select partners",
    partner: "Capital One",
    endsOn: "Ends Sunday",
    perk: "1.25 → 1 transfer ratio on 3 partners",
    tags: ["capital-one", "transfer-partners", "deals"],
  },
  {
    id: "deal-chase-hyatt",
    title: "Chase → Hyatt at 1:1.25 for one week only",
    partner: "Chase Ultimate Rewards",
    endsOn: "Ends in 4 days",
    perk: "20k UR → 25k Hyatt points",
    tags: ["chase", "hyatt", "transfer-partners", "luxury-hotels", "deals"],
  },
  {
    id: "deal-marriott-pointsale",
    title: "Marriott points sale: 40% off purchases",
    partner: "Marriott Bonvoy",
    endsOn: "Ends in 11 days",
    perk: "Buy points at 0.85¢ each — under their value",
    tags: ["marriott", "luxury-hotels", "deals"],
  },
  {
    id: "deal-united-fall",
    title: "United fall sale: 35k miles to Europe roundtrip",
    partner: "United MileagePlus",
    endsOn: "Through Sep 30",
    perk: "Saver-level fares to 24 European cities",
    tags: ["united", "europe", "award-bookings", "deals"],
  },
  {
    id: "deal-delta-flash",
    title: "Delta flash sale: 12k miles to the Caribbean",
    partner: "Delta SkyMiles",
    endsOn: "Limited dates · book by Sunday",
    perk: "Roundtrip awards to 8 islands at 12k",
    tags: ["delta", "caribbean", "award-bookings", "deals", "family-travel"],
  },
  {
    id: "deal-hyatt-suite-upgrade",
    title: "Hyatt suite-upgrade certificate event",
    partner: "World of Hyatt",
    endsOn: "Through Oct 15",
    perk: "Earn an extra TSU at 50 nights this year",
    tags: ["hyatt", "luxury-hotels", "advanced", "deals"],
  },
  {
    id: "deal-aeroplan-transfer",
    title: "Capital One → Air Canada: 20% bonus",
    partner: "Capital One Miles",
    endsOn: "Ends in 8 days",
    perk: "Stretch Aeroplan sweet spots to the long-haul",
    tags: ["capital-one", "transfer-partners", "award-bookings", "premium-cabin", "deals", "advanced"],
  },
  {
    id: "deal-aa-saver",
    title: "American AAdvantage: 22.5k Hawaii saver awards",
    partner: "American Airlines",
    endsOn: "Open inventory · book by Aug 1",
    perk: "Lower-than-usual saver pricing to all islands",
    tags: ["american", "hawaii", "award-bookings", "family-travel", "deals", "beginner"],
  },
  {
    id: "deal-ihg-bonus",
    title: "IHG: 4x points on every stay",
    partner: "IHG One Rewards",
    endsOn: "Through Sep 15",
    perk: "Quadruple base earning for two stays or more",
    tags: ["luxury-hotels", "deals", "intermediate"],
  },
  {
    id: "deal-bonvoy-elite",
    title: "Marriott: 3x elite night credits this fall",
    partner: "Marriott Bonvoy",
    endsOn: "Through Nov 30",
    perk: "Earn elite status on a third of the usual stays",
    tags: ["marriott", "luxury-hotels", "advanced", "deals"],
  },
  {
    id: "deal-amex-charles",
    title: "Amex MR → Aer Lingus at 1:1.4",
    partner: "Amex Membership Rewards",
    endsOn: "Ends in 9 days",
    perk: "Cheapest path to Europe via Avios partners",
    tags: ["amex", "transfer-partners", "europe", "award-bookings", "deals", "advanced"],
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "dest-japan",
    name: "Tokyo & Kyoto, Japan",
    region: "Asia",
    bestMonths: "Mar – May · Oct – Nov",
    pointsTip: "Business class from 60k miles one-way via alliance partner",
    tags: ["japan", "premium-cabin", "intermediate"],
    accent: "from-rose-500 to-tpg-blue",
  },
  {
    id: "dest-iceland",
    name: "Reykjavík, Iceland",
    region: "Europe",
    bestMonths: "Feb – Mar (aurora)",
    pointsTip: "Stopover routings through European hubs save 20% in miles",
    tags: ["iceland", "europe"],
    accent: "from-indigo-500 to-tpg-teal",
  },
  {
    id: "dest-italy",
    name: "Amalfi Coast, Italy",
    region: "Europe",
    bestMonths: "May – Jun · Sep",
    pointsTip: "Fly into Naples on points, train down — saves 18k miles",
    tags: ["italy", "europe", "luxury-hotels"],
    accent: "from-amber-500 to-rose-500",
  },
  {
    id: "dest-thailand",
    name: "Bangkok & Phuket, Thailand",
    region: "Asia",
    bestMonths: "Nov – Mar",
    pointsTip: "Premium cabin sweet spot via Asian alliance partners",
    tags: ["thailand", "premium-cabin"],
    accent: "from-emerald-500 to-tpg-teal",
  },
  {
    id: "dest-hawaii",
    name: "Maui & Kauai, Hawaii",
    region: "USA",
    bestMonths: "Apr – Jun · Sep – Oct",
    pointsTip: "Coach from 22.5k miles one-way; routinely opens 60 days out",
    tags: ["hawaii", "family-travel", "beginner"],
    accent: "from-emerald-500 to-tpg-blue",
  },
  {
    id: "dest-caribbean",
    name: "Turks & Caicos",
    region: "Caribbean",
    bestMonths: "Nov – Apr",
    pointsTip: "Hyatt & Marriott have award sweet spots under 50k pts/night",
    tags: ["caribbean", "luxury-hotels", "hyatt", "marriott"],
    accent: "from-tpg-teal to-emerald-400",
  },
  {
    id: "dest-hokkaido",
    name: "Hokkaido, Japan",
    region: "Asia",
    bestMonths: "Jan – Feb (powder) · Jul – Aug",
    pointsTip: "JAL business class via Tokyo for 55k points round-trip during low season",
    tags: ["japan", "premium-cabin", "advanced"],
    accent: "from-sky-500 to-indigo-500",
  },
  {
    id: "dest-lisbon",
    name: "Lisbon, Portugal",
    region: "Europe",
    bestMonths: "Apr – Jun · Sep – Oct",
    pointsTip: "TAP releases generous award space; Lisbon is the cheapest European gateway in 2026",
    tags: ["europe", "trip-planning", "premium-cabin"],
    accent: "from-amber-400 to-rose-500",
  },
  {
    id: "dest-paris",
    name: "Paris, France",
    region: "Europe",
    bestMonths: "May – Jun · Sep",
    pointsTip: "Hyatt Vendôme + Park Hyatt Place: two of the strongest Hyatt redemptions in Europe",
    tags: ["europe", "luxury-hotels", "hyatt"],
    accent: "from-fuchsia-500 to-tpg-blue",
  },
  {
    id: "dest-london",
    name: "London, UK",
    region: "Europe",
    bestMonths: "May – Sep",
    pointsTip: "Avoid BA's fuel surcharges by transferring to Virgin or Aer Lingus instead",
    tags: ["europe", "transfer-partners", "intermediate"],
    accent: "from-tpg-navy to-tpg-blue",
  },
  {
    id: "dest-tuscany",
    name: "Tuscany, Italy",
    region: "Europe",
    bestMonths: "May – Jun · Sep – Oct",
    pointsTip: "Fly into Rome on miles, train up — saves 14k miles vs flying to Florence",
    tags: ["italy", "europe", "luxury-hotels", "trip-planning"],
    accent: "from-emerald-500 to-amber-400",
  },
  {
    id: "dest-chiang-mai",
    name: "Chiang Mai, Thailand",
    region: "Asia",
    bestMonths: "Nov – Feb",
    pointsTip: "Hyatt Regency Chiang Mai books at 12k pts/night — one of Asia's best values",
    tags: ["thailand", "hyatt", "budget", "luxury-hotels"],
    accent: "from-orange-500 to-emerald-500",
  },
  {
    id: "dest-oahu",
    name: "Oahu, Hawaii",
    region: "USA",
    bestMonths: "Apr – Jun · Sep – Oct",
    pointsTip: "United and Hawaiian both run 22.5k mile awards from West Coast hubs",
    tags: ["hawaii", "united", "family-travel", "beginner"],
    accent: "from-cyan-500 to-tpg-blue",
  },
  {
    id: "dest-st-lucia",
    name: "St. Lucia",
    region: "Caribbean",
    bestMonths: "Dec – Apr",
    pointsTip: "Marriott Cap Estate at 35k points/night — under half its cash rate",
    tags: ["caribbean", "luxury-hotels", "marriott", "trip-planning"],
    accent: "from-tpg-teal-deep to-amber-400",
  },
  {
    id: "dest-aruba",
    name: "Aruba",
    region: "Caribbean",
    bestMonths: "Apr – Jul (dry season)",
    pointsTip: "Hyatt Regency Aruba is a sweet spot at 17.5k pts/night",
    tags: ["caribbean", "hyatt", "luxury-hotels", "family-travel"],
    accent: "from-orange-500 to-amber-400",
  },
];

export const TRAVEL_GOAL_OPTIONS = [
  { id: "free-flights", label: "Free flights" },
  { id: "luxury-hotels", label: "Luxury hotels" },
  { id: "earn-status", label: "Earn elite status" },
  { id: "premium-cabin", label: "Fly business / first class" },
  { id: "family-trip", label: "A big family trip" },
  { id: "honeymoon", label: "A honeymoon or milestone trip" },
];

export const DREAM_DEST_OPTIONS: { id: import("./types").Tag; label: string; emoji: string }[] = [
  { id: "japan", label: "Japan", emoji: "🗾" },
  { id: "europe", label: "Europe", emoji: "🏛️" },
  { id: "italy", label: "Italy", emoji: "🇮🇹" },
  { id: "iceland", label: "Iceland", emoji: "❄️" },
  { id: "thailand", label: "Thailand", emoji: "🌴" },
  { id: "hawaii", label: "Hawaii", emoji: "🏝️" },
  { id: "caribbean", label: "Caribbean", emoji: "🐚" },
];

export const SPEND_OPTIONS: { id: import("./types").Tag; label: string; emoji: string }[] = [
  { id: "dining", label: "Dining out", emoji: "🍽️" },
  { id: "groceries", label: "Groceries", emoji: "🛒" },
  { id: "travel-spend", label: "Travel", emoji: "✈️" },
  { id: "gas", label: "Gas / commute", emoji: "⛽" },
];

export const BRAND_OPTIONS: { id: import("./types").Tag; label: string }[] = [
  { id: "united", label: "United" },
  { id: "delta", label: "Delta" },
  { id: "american", label: "American" },
  { id: "hyatt", label: "Hyatt" },
  { id: "marriott", label: "Marriott" },
];

export const COMMON_CARDS = [
  { id: "tpg-freedom", label: "Skyline Freedom Starter (no annual fee)" },
  { id: "tpg-sapphire-preferred", label: "Skyline Sapphire Preferred" },
  { id: "tpg-gold", label: "Northstar Gold Rewards" },
  { id: "tpg-venture-x", label: "Compass Venture X" },
  { id: "tpg-platinum", label: "Atlas Platinum Elite" },
];
